### ISSUE TITLE
Test Template can't get keyword from resource

### ISSUE THREAD

**Issue by sharpdeep** [Snooz82/robotframework-datadriver#10]
I import resource file  contains keywords, and want to use it as a test template.

however, I found that it can only get the keyword from current testsuite.

```
    def _get_template_keyword(self, suite):
        template = self.template_test.template
        if template:
            for keyword in suite.resource.keywords:
                if self._is_same_keyword(keyword.name, template):
                    return keyword
        raise AttributeError('No "Test Template" keyword found for first test case.')
```

`suite.resource.keywords` only get the current testsuite keyword. 

can `robotframework-datadriver` support to use external keyword as template ?

**Comment by Snooz82** [comment]
Hi,

As mentioned in documentation it is not possible to use external Keyword as Template.
Reason are the names of arguments.

https://github.com/Snooz82/robotframework-datadriver/blob/master/Readme.rst#requirements

I would also not recommend to do this, because it would be quite in-transparent to use an external keyword as test. In this case you can not read in TestSuite what the Test is doing.

Anyhow you can workaround this by just adding one local Keyword that calls the “external” Keyword. As Template you use the local one.
