### ISSUE TITLE
Custom reader from absolut path

### ISSUE THREAD

**Issue by WillyWinkel** [Snooz82/robotframework-datadriver#14]
I want to create a custom reader, which is located within my sources.
Therefore it would be neat to be able to pass an absolut path to the DataDriver settings and tell it where my custom reader is.
See push request #13

**Comment by Snooz82** [comment]
Hi ~~Len..~~ Ähm Willy,

i merged you PR, but i want to impove this functionality that it is also possible to use just a Class name.
Example you write your file indexer and you create a setup.py for it, so that it can be distributed to the test systems properly.
It should be possible to just import them by ClassName.

Cheers + C U
René

**Comment by Snooz82** [comment]
@WillyWinkel 
Could you check out new Version 0.3.4.

Does this fit your needs?
Thanks for your contribution!

**Comment by WillyWinkel** [comment]
Working like a charm
