### ISSUE TITLE
basic example doesn't seem to work

### ISSUE THREAD

**Issue by jdnr** [Snooz82/robotframework-datadriver#23]
Hi Rene,

I'm using RoboCloud Editor "Robocode Lab".

The basic example doesn't seem to work.

1. I have to define the Template Keyword before the section Test Cases, or when running the robot complains it cannot find such keyword.

2. It raises an exception when declaring the DataDriver Library, however I can get away by not declaring it, which seems a bit odd not having to declare the Library under settings.

3. It skips the first argument

Please see attachments

Thanks,
Daniel
<img width="800" alt="Screenshot 2020-07-03 at 12 48 37" src="https://user-images.githubusercontent.com/12010562/86466835-4ad67200-bd2c-11ea-8a7b-494c3feba816.png">
<img width="800" alt="Screenshot 2020-07-03 at 12 44 51" src="https://user-images.githubusercontent.com/12010562/86466864-56299d80-bd2c-11ea-98ef-9a9dca0e9471.png">

**Comment by osrjv** [comment]
Hi,

I can comment on these from Robocode Lab side of things.

1. This is due to how notebooks work. It runs a cell one-by-one so the keywords would not have been evaluated yet when the test cases are run, unless you run them manually in a different order instead of pressing run all. You can fix it like you have here, or by having the test cases and keywords in the same cell.

2. The datadriver library assumes there is a csv file with the same name as the robot file in the same folder, and that seems to be missing. However, normal test/task templates are a built-in feature of Robot Framework and work just fine without datadriver.

3. I could replicate this in my notebook and that seems to be a bug in the notebook feature of Robocode Lab itself and is not related to datadriver. We will create an issue out of this.

**Comment by Snooz82** [comment]
Hi, 

Yes. You are not really using DataDriver.
Your two tests are "normal" basic Robot Test Templates.

Regards
René
