### ISSUE TITLE
Test Teardown broken in DataDriver latest versions

### ISSUE THREAD

**Issue by Veronit** [Snooz82/robotframework-datadriver#44]
Stumbled on this problem. Task/Test Teardown works on DataDriver version 1.0.0 but on the newer ones. Using RF version 3.2.2.
Attached is a sample test and log.html's for executions.

Teardown works if you add it to the Task/Test Template keyword.
[datadriver.zip](https://github.com/Snooz82/robotframework-datadriver/files/6441259/datadriver.zip)

Same thing as in https://github.com/Snooz82/robotframework-datadriver/issues/41

**Comment by frankyqa** [comment]
Facing the same issue with this setup.

**Comment by Snooz82** [comment]
@Veronit @frankyqa 

I got that bug now.
I could not reproduce it with the original issue, because i did not try it with RF 3.2.2

I would actually consider that more a bug in 3.2.2 than in DataDriver 😜 but i made changes with new RF 4.0 and then that happend, so it was my fault.

The "Issue" was that when DD is creating these test before i created Setup then Body then Teardown.
With 1.1.1 i changed that for better code structure to Setup & Teardown and then Body.
RF 3.2.2 for some reason then deletes the Teardown again, when you create a body... 🥴

Long talk short.
Fixed it.
