### ISSUE TITLE
Create empty list in @{list}-cell

### ISSUE THREAD

**Issue by dVoo** [Snooz82/robotframework-datadriver#48]
Empty cells are read as list with single-entry empty string `[ '' ]`, not as empty list `[ ]`.
Is this behavior intended and is it possible to create an empty list without using python literals?

Behavior tested with xls and csv input with both v1.2.0 and v1.3.0.

CSV to reproduce:
```
*** Test Cases ***;@{list1};e{list2}
CheckList1;not,empty,list;['not','empty','list']
CheckList2;;[]
```

**Comment by Snooz82** [comment]
Hi Daniel,

UPS!

You found a bug.
And my automated test did not.

There was also a bug in the test, because i had that as a test case but i implemented the tests wrong.
;-) 

Now an empty list is created as you did and a list with an empty string is created by using `${Empty}` as value

Thanks
@dVoo

**Comment by dVoo** [comment]
So cool.
Keep up the amazing work.
Thanks a lot for the fix.
