### ISSUE TITLE
tags usage for robotframework-datadriver

### ISSUE THREAD

**Issue by davesliu** [Snooz82/robotframework-datadriver#51]
Hello,

I'm using Robot Framework 3.2.1 (Python 3.7.7 on win32) with robotframework-datadriver Version: 0.3.6.
With this 0.3.6 version, I set the force Tags for test.robot file with Tag_1 and Tag_2, in the Excel data-driven table, I marked some lines with Tag_1 and some line with Tag_2.
When run the test.robot file with  command 
       robot  -e Tag_1 -i Tag_2 test.robot
It failed to show that 
    It contains no tests matching tag 'Tag_2' and not matching tag 'Tag_1'.

So how can I run the lines with marked Tag_2?

BTW, if we want to upgrade  robotframework-datadriver to newer version with still keep using Robotframework 3.2.1, which version can I use?

Thanks in advance

**Comment by Snooz82** [comment]
Hi,

here Robot Framework itself deletes the whole suite, because you explicitly excluded Tag_1. 

Just make --include Tag_2 to only execute these. No need to exclude the others.

updating should not be an issue.
DataDriver 1.4.1 should be compatible to RF3.2

what is blocking you from upgrading to RF 4?

**Comment by davesliu** [comment]
@Snooz82 
Thanks for your detail comments. It works for just include Tag_2 :-)
I will upgrade DataDriver  to 1.4.1 
For not upgrading to RF4, as currently we use a lot of RF3 syntax  like 'Run keywords If' and the For loop in .robot files, not sure if it can be compatible with RF4.
