### ISSUE TITLE
[feature request] Allow declaring a TestCaseData as skipped

### ISSUE THREAD

**Issue by Apteryks** [Snooz82/robotframework-datadriver#68]
Hello,

Pytest allows dynamically marking parameterized test as skipped, which has the benefit to clearly show which tests were skipped in the output.

There doesn't seem to be a way to do this with DataDriver, hence I'm opening this feature request (as requested on #datadriver in Slack)

Thank you!

**Comment by Snooz82** [comment]
I will close that issue due to the fact, that there is a feature that can create this functionality 

robot suite:
```robotframework
*** Settings ***
Library     DataDriver
Test Template    Template

*** Test Cases ***
Testcase ${arg}    Hello

*** Keywords ***
Template
    [Arguments]    ${arg}
    Log    ${arg}
```
   
csv:
```
*** Test Cases ***;${arg};[Tags]
;Hello;one
;World;two
;SKIPPED;three,robot:SKIP
;executed;four
```

command:
`❯ robot --skip robot:SKIP dd.robot

I create a Robot Framework issue to automatically use the tags `robot:skip` to skip tests.
until this feature is implemented, you can use `--skip robot:skip` to skip these tests.

https://github.com/robotframework/robotframework/issues/4161

**Comment by Apteryks** [comment]
Thanks for sharing this trick and opening an issue with robotframework!
